### ISSUE TITLE
I have a probleme that I can't solve it , please help

### ISSUE THREAD

**Issue by emira49494** [GoogleChrome/sw-toolbox#150]
ionic.bundle.js:43924 WARNING: Tried to load angular more than once.
controllers.js:1 Uncaught ReferenceError: controllers is not defined(anonymous function) @ controllers.js:1
services.js:1 Uncaught ReferenceError: services is not defined(anonymous function) @ services.js:1
angular.js:13642 Error: [ng:areq] http://errors.angularjs.org/1.5.6/ng/areq?p0=MainCtrl&p1=not%20a%20function%2C%20got%20undefined
    at Error (native)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.5.6/angular.min.js:6:412
    at sb (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.6/angular.min.js:23:157)
    at Qa (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.6/angular.min.js:23:244)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.5.6/angular.min.js:89:273
    at $f (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.6/angular.min.js:72:260)
    at n (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.6/angular.min.js:64:146)
    at g (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.6/angular.min.js:58:429)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.5.6/angular.min.js:58:67
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.5.6/angular.min.js:21:161

**Comment by wibblymat** [comment]
Doesn't appear to be related to sw-toolbox
